// Code generated by ent, DO NOT EDIT.

package tiktokcreator

import (
	"time"
)

const (
	// Label holds the string label denoting the tiktokcreator type in the database.
	Label = "tiktok_creator"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldCreatorID holds the string denoting the creator_id field in the database.
	FieldCreatorID = "creator_id"
	// FieldCreatorName holds the string denoting the creator_name field in the database.
	FieldCreatorName = "creator_name"
	// FieldCreatorNickname holds the string denoting the creator_nickname field in the database.
	FieldCreatorNickname = "creator_nickname"
	// FieldRegion holds the string denoting the region field in the database.
	FieldRegion = "region"
	// FieldProductCategories holds the string denoting the product_categories field in the database.
	FieldProductCategories = "product_categories"
	// FieldFollowerCount holds the string denoting the follower_count field in the database.
	FieldFollowerCount = "follower_count"
	// FieldVideoAvgViewCnt holds the string denoting the video_avg_view_cnt field in the database.
	FieldVideoAvgViewCnt = "video_avg_view_cnt"
	// FieldVideoPubCnt holds the string denoting the video_pub_cnt field in the database.
	FieldVideoPubCnt = "video_pub_cnt"
	// FieldEcVideoAvgViewCnt holds the string denoting the ec_video_avg_view_cnt field in the database.
	FieldEcVideoAvgViewCnt = "ec_video_avg_view_cnt"
	// FieldCreatorOecuid holds the string denoting the creator_oecuid field in the database.
	FieldCreatorOecuid = "creator_oecuid"
	// FieldCreatorTtuid holds the string denoting the creator_ttuid field in the database.
	FieldCreatorTtuid = "creator_ttuid"
	// Table holds the table name of the tiktokcreator in the database.
	Table = "tiktok_creators"
)

// Columns holds all SQL columns for tiktokcreator fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldCreatorID,
	FieldCreatorName,
	FieldCreatorNickname,
	FieldRegion,
	FieldProductCategories,
	FieldFollowerCount,
	FieldVideoAvgViewCnt,
	FieldVideoPubCnt,
	FieldEcVideoAvgViewCnt,
	FieldCreatorOecuid,
	FieldCreatorTtuid,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// CreatorIDValidator is a validator for the "creator_id" field. It is called by the builders before save.
	CreatorIDValidator func(string) error
	// CreatorNameValidator is a validator for the "creator_name" field. It is called by the builders before save.
	CreatorNameValidator func(string) error
	// CreatorNicknameValidator is a validator for the "creator_nickname" field. It is called by the builders before save.
	CreatorNicknameValidator func(string) error
	// RegionValidator is a validator for the "region" field. It is called by the builders before save.
	RegionValidator func(string) error
	// DefaultProductCategories holds the default value on creation for the "product_categories" field.
	DefaultProductCategories []string
	// DefaultFollowerCount holds the default value on creation for the "follower_count" field.
	DefaultFollowerCount uint32
	// DefaultVideoAvgViewCnt holds the default value on creation for the "video_avg_view_cnt" field.
	DefaultVideoAvgViewCnt uint32
	// DefaultVideoPubCnt holds the default value on creation for the "video_pub_cnt" field.
	DefaultVideoPubCnt uint32
	// DefaultEcVideoAvgViewCnt holds the default value on creation for the "ec_video_avg_view_cnt" field.
	DefaultEcVideoAvgViewCnt uint32
	// DefaultCreatorOecuid holds the default value on creation for the "creator_oecuid" field.
	DefaultCreatorOecuid string
	// DefaultCreatorTtuid holds the default value on creation for the "creator_ttuid" field.
	DefaultCreatorTtuid string
)
