// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/4meepo/tiktok-tools/ent/creator"
	"github.com/4meepo/tiktok-tools/ent/schema"
	"github.com/4meepo/tiktok-tools/ent/tiktokcreator"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	creatorMixin := schema.Creator{}.Mixin()
	creatorMixinFields0 := creatorMixin[0].Fields()
	_ = creatorMixinFields0
	creatorFields := schema.Creator{}.Fields()
	_ = creatorFields
	// creatorDescCreateTime is the schema descriptor for create_time field.
	creatorDescCreateTime := creatorMixinFields0[0].Descriptor()
	// creator.DefaultCreateTime holds the default value on creation for the create_time field.
	creator.DefaultCreateTime = creatorDescCreateTime.Default.(func() time.Time)
	// creatorDescUpdateTime is the schema descriptor for update_time field.
	creatorDescUpdateTime := creatorMixinFields0[1].Descriptor()
	// creator.DefaultUpdateTime holds the default value on creation for the update_time field.
	creator.DefaultUpdateTime = creatorDescUpdateTime.Default.(func() time.Time)
	// creator.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	creator.UpdateDefaultUpdateTime = creatorDescUpdateTime.UpdateDefault.(func() time.Time)
	// creatorDescXzid is the schema descriptor for xzid field.
	creatorDescXzid := creatorFields[0].Descriptor()
	// creator.XzidValidator is a validator for the "xzid" field. It is called by the builders before save.
	creator.XzidValidator = creatorDescXzid.Validators[0].(func(string) error)
	// creatorDescUniqueID is the schema descriptor for unique_id field.
	creatorDescUniqueID := creatorFields[1].Descriptor()
	// creator.UniqueIDValidator is a validator for the "unique_id" field. It is called by the builders before save.
	creator.UniqueIDValidator = creatorDescUniqueID.Validators[0].(func(string) error)
	// creatorDescNickName is the schema descriptor for nick_name field.
	creatorDescNickName := creatorFields[2].Descriptor()
	// creator.NickNameValidator is a validator for the "nick_name" field. It is called by the builders before save.
	creator.NickNameValidator = creatorDescNickName.Validators[0].(func(string) error)
	// creatorDescRegion is the schema descriptor for region field.
	creatorDescRegion := creatorFields[3].Descriptor()
	// creator.RegionValidator is a validator for the "region" field. It is called by the builders before save.
	creator.RegionValidator = creatorDescRegion.Validators[0].(func(string) error)
	// creatorDescCreatorID is the schema descriptor for creator_id field.
	creatorDescCreatorID := creatorFields[5].Descriptor()
	// creator.DefaultCreatorID holds the default value on creation for the creator_id field.
	creator.DefaultCreatorID = creatorDescCreatorID.Default.(string)
	// creator.CreatorIDValidator is a validator for the "creator_id" field. It is called by the builders before save.
	creator.CreatorIDValidator = creatorDescCreatorID.Validators[0].(func(string) error)
	// creatorDescCreatorOecuid is the schema descriptor for creator_oecuid field.
	creatorDescCreatorOecuid := creatorFields[6].Descriptor()
	// creator.DefaultCreatorOecuid holds the default value on creation for the creator_oecuid field.
	creator.DefaultCreatorOecuid = creatorDescCreatorOecuid.Default.(string)
	// creator.CreatorOecuidValidator is a validator for the "creator_oecuid" field. It is called by the builders before save.
	creator.CreatorOecuidValidator = creatorDescCreatorOecuid.Validators[0].(func(string) error)
	// creatorDescCate1NameCn is the schema descriptor for cate1_name_cn field.
	creatorDescCate1NameCn := creatorFields[7].Descriptor()
	// creator.DefaultCate1NameCn holds the default value on creation for the cate1_name_cn field.
	creator.DefaultCate1NameCn = creatorDescCate1NameCn.Default.([]string)
	// creatorDescTiktokCategory is the schema descriptor for tiktok_category field.
	creatorDescTiktokCategory := creatorFields[8].Descriptor()
	// creator.DefaultTiktokCategory holds the default value on creation for the tiktok_category field.
	creator.DefaultTiktokCategory = creatorDescTiktokCategory.Default.([]string)
	// creatorDescEmail is the schema descriptor for email field.
	creatorDescEmail := creatorFields[9].Descriptor()
	// creator.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	creator.EmailValidator = creatorDescEmail.Validators[0].(func(string) error)
	// creatorDescWhatsapp is the schema descriptor for whatsapp field.
	creatorDescWhatsapp := creatorFields[10].Descriptor()
	// creator.WhatsappValidator is a validator for the "whatsapp" field. It is called by the builders before save.
	creator.WhatsappValidator = creatorDescWhatsapp.Validators[0].(func(string) error)
	tiktokcreatorMixin := schema.TiktokCreator{}.Mixin()
	tiktokcreatorMixinFields0 := tiktokcreatorMixin[0].Fields()
	_ = tiktokcreatorMixinFields0
	tiktokcreatorFields := schema.TiktokCreator{}.Fields()
	_ = tiktokcreatorFields
	// tiktokcreatorDescCreateTime is the schema descriptor for create_time field.
	tiktokcreatorDescCreateTime := tiktokcreatorMixinFields0[0].Descriptor()
	// tiktokcreator.DefaultCreateTime holds the default value on creation for the create_time field.
	tiktokcreator.DefaultCreateTime = tiktokcreatorDescCreateTime.Default.(func() time.Time)
	// tiktokcreatorDescUpdateTime is the schema descriptor for update_time field.
	tiktokcreatorDescUpdateTime := tiktokcreatorMixinFields0[1].Descriptor()
	// tiktokcreator.DefaultUpdateTime holds the default value on creation for the update_time field.
	tiktokcreator.DefaultUpdateTime = tiktokcreatorDescUpdateTime.Default.(func() time.Time)
	// tiktokcreator.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	tiktokcreator.UpdateDefaultUpdateTime = tiktokcreatorDescUpdateTime.UpdateDefault.(func() time.Time)
	// tiktokcreatorDescCreatorID is the schema descriptor for creator_id field.
	tiktokcreatorDescCreatorID := tiktokcreatorFields[0].Descriptor()
	// tiktokcreator.CreatorIDValidator is a validator for the "creator_id" field. It is called by the builders before save.
	tiktokcreator.CreatorIDValidator = tiktokcreatorDescCreatorID.Validators[0].(func(string) error)
	// tiktokcreatorDescCreatorName is the schema descriptor for creator_name field.
	tiktokcreatorDescCreatorName := tiktokcreatorFields[1].Descriptor()
	// tiktokcreator.CreatorNameValidator is a validator for the "creator_name" field. It is called by the builders before save.
	tiktokcreator.CreatorNameValidator = tiktokcreatorDescCreatorName.Validators[0].(func(string) error)
	// tiktokcreatorDescCreatorNickname is the schema descriptor for creator_nickname field.
	tiktokcreatorDescCreatorNickname := tiktokcreatorFields[2].Descriptor()
	// tiktokcreator.CreatorNicknameValidator is a validator for the "creator_nickname" field. It is called by the builders before save.
	tiktokcreator.CreatorNicknameValidator = tiktokcreatorDescCreatorNickname.Validators[0].(func(string) error)
	// tiktokcreatorDescRegion is the schema descriptor for region field.
	tiktokcreatorDescRegion := tiktokcreatorFields[3].Descriptor()
	// tiktokcreator.RegionValidator is a validator for the "region" field. It is called by the builders before save.
	tiktokcreator.RegionValidator = tiktokcreatorDescRegion.Validators[0].(func(string) error)
	// tiktokcreatorDescProductCategories is the schema descriptor for product_categories field.
	tiktokcreatorDescProductCategories := tiktokcreatorFields[4].Descriptor()
	// tiktokcreator.DefaultProductCategories holds the default value on creation for the product_categories field.
	tiktokcreator.DefaultProductCategories = tiktokcreatorDescProductCategories.Default.([]string)
	// tiktokcreatorDescFollowerCount is the schema descriptor for follower_count field.
	tiktokcreatorDescFollowerCount := tiktokcreatorFields[5].Descriptor()
	// tiktokcreator.DefaultFollowerCount holds the default value on creation for the follower_count field.
	tiktokcreator.DefaultFollowerCount = tiktokcreatorDescFollowerCount.Default.(uint32)
	// tiktokcreatorDescVideoAvgViewCnt is the schema descriptor for video_avg_view_cnt field.
	tiktokcreatorDescVideoAvgViewCnt := tiktokcreatorFields[6].Descriptor()
	// tiktokcreator.DefaultVideoAvgViewCnt holds the default value on creation for the video_avg_view_cnt field.
	tiktokcreator.DefaultVideoAvgViewCnt = tiktokcreatorDescVideoAvgViewCnt.Default.(uint32)
	// tiktokcreatorDescVideoPubCnt is the schema descriptor for video_pub_cnt field.
	tiktokcreatorDescVideoPubCnt := tiktokcreatorFields[7].Descriptor()
	// tiktokcreator.DefaultVideoPubCnt holds the default value on creation for the video_pub_cnt field.
	tiktokcreator.DefaultVideoPubCnt = tiktokcreatorDescVideoPubCnt.Default.(uint32)
	// tiktokcreatorDescEcVideoAvgViewCnt is the schema descriptor for ec_video_avg_view_cnt field.
	tiktokcreatorDescEcVideoAvgViewCnt := tiktokcreatorFields[8].Descriptor()
	// tiktokcreator.DefaultEcVideoAvgViewCnt holds the default value on creation for the ec_video_avg_view_cnt field.
	tiktokcreator.DefaultEcVideoAvgViewCnt = tiktokcreatorDescEcVideoAvgViewCnt.Default.(uint32)
	// tiktokcreatorDescCreatorOecuid is the schema descriptor for creator_oecuid field.
	tiktokcreatorDescCreatorOecuid := tiktokcreatorFields[9].Descriptor()
	// tiktokcreator.DefaultCreatorOecuid holds the default value on creation for the creator_oecuid field.
	tiktokcreator.DefaultCreatorOecuid = tiktokcreatorDescCreatorOecuid.Default.(string)
	// tiktokcreatorDescCreatorTtuid is the schema descriptor for creator_ttuid field.
	tiktokcreatorDescCreatorTtuid := tiktokcreatorFields[10].Descriptor()
	// tiktokcreator.DefaultCreatorTtuid holds the default value on creation for the creator_ttuid field.
	tiktokcreator.DefaultCreatorTtuid = tiktokcreatorDescCreatorTtuid.Default.(string)
}
