// Code generated by ent, DO NOT EDIT.

package creator

import (
	"time"
)

const (
	// Label holds the string label denoting the creator type in the database.
	Label = "creator"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldXzid holds the string denoting the xzid field in the database.
	FieldXzid = "xzid"
	// FieldUniqueID holds the string denoting the unique_id field in the database.
	FieldUniqueID = "unique_id"
	// FieldNickName holds the string denoting the nick_name field in the database.
	FieldNickName = "nick_name"
	// FieldRegion holds the string denoting the region field in the database.
	FieldRegion = "region"
	// FieldFollowerNum holds the string denoting the follower_num field in the database.
	FieldFollowerNum = "follower_num"
	// FieldCreatorID holds the string denoting the creator_id field in the database.
	FieldCreatorID = "creator_id"
	// FieldCreatorOecuid holds the string denoting the creator_oecuid field in the database.
	FieldCreatorOecuid = "creator_oecuid"
	// FieldCate1NameCn holds the string denoting the cate1_name_cn field in the database.
	FieldCate1NameCn = "cate1_name_cn"
	// FieldTiktokCategory holds the string denoting the tiktok_category field in the database.
	FieldTiktokCategory = "tiktok_category"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldWhatsapp holds the string denoting the whatsapp field in the database.
	FieldWhatsapp = "whatsapp"
	// Table holds the table name of the creator in the database.
	Table = "creators"
)

// Columns holds all SQL columns for creator fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldXzid,
	FieldUniqueID,
	FieldNickName,
	FieldRegion,
	FieldFollowerNum,
	FieldCreatorID,
	FieldCreatorOecuid,
	FieldCate1NameCn,
	FieldTiktokCategory,
	FieldEmail,
	FieldWhatsapp,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// XzidValidator is a validator for the "xzid" field. It is called by the builders before save.
	XzidValidator func(string) error
	// UniqueIDValidator is a validator for the "unique_id" field. It is called by the builders before save.
	UniqueIDValidator func(string) error
	// NickNameValidator is a validator for the "nick_name" field. It is called by the builders before save.
	NickNameValidator func(string) error
	// RegionValidator is a validator for the "region" field. It is called by the builders before save.
	RegionValidator func(string) error
	// DefaultCreatorID holds the default value on creation for the "creator_id" field.
	DefaultCreatorID string
	// CreatorIDValidator is a validator for the "creator_id" field. It is called by the builders before save.
	CreatorIDValidator func(string) error
	// DefaultCreatorOecuid holds the default value on creation for the "creator_oecuid" field.
	DefaultCreatorOecuid string
	// CreatorOecuidValidator is a validator for the "creator_oecuid" field. It is called by the builders before save.
	CreatorOecuidValidator func(string) error
	// DefaultCate1NameCn holds the default value on creation for the "cate1_name_cn" field.
	DefaultCate1NameCn []string
	// DefaultTiktokCategory holds the default value on creation for the "tiktok_category" field.
	DefaultTiktokCategory []string
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// WhatsappValidator is a validator for the "whatsapp" field. It is called by the builders before save.
	WhatsappValidator func(string) error
)
