// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// TiktokCreator is the predicate function for tiktokcreator builders.
type TiktokCreator func(*sql.Selector)
